_BASE_: "../../SWIN-RCNN-FPN-OWOD.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/swin_tiny_patch4_window7_224_d2.pth"
DATASETS:
  TRAIN: ('t1_voc_coco_2007_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', 't1_voc_coco_2007_known_test')   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/home/appuser/OWOD/output/t1"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 20
