_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "swin_tiny_patch4_window7_224_d2.pth"
  MASK_ON: False
  ROI_HEADS:
    #    NUM_CLASSES: 81 # 0-79 Known class; 80 -> Unknown; 81 -> Background.
    NUM_CLASSES: 81
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
SOLVER:
  # always reduce lr by 10X in the last 60k and 20k iterations 
  # Kaiming et al,Rethinking ImageNet Pre-training,2018
  STEPS: (90000, 94000) 
  # 1X learning schedule ~=12 epochs
  MAX_ITER: 96000
  WEIGHT_DECAY: 0.05
  # less gpu should use smaller lr, linear rule 
  # Priya Goyal et al, Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour
  BASE_LR: 0.00001
  WARMUP_ITERS: 800
  AMP:
    ENABLED: True
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
VERSION: 2
OWOD:
  ENABLE_THRESHOLD_AUTOLABEL_UNK: True
  NUM_UNK_PER_IMAGE: 1
  ENABLE_UNCERTAINITY_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: True
  FEATURE_STORE_SAVE_PATH: 'feature_store'
  CLUSTERING:
    ITEMS_PER_CLASS: 20
    START_ITER: 1000
    UPDATE_MU_ITER: 3000
    MOMENTUM: 0.99
    Z_DIMENSION: 128